### ISSUE TITLE
Stuck at S3 Copy Status

### ISSUE THREAD

**Issue by AmudhaNila** [awslabs/aws-gov-cloud-import#10]
When copying from us-east-2 to us-gov-east-1, my image import became stuck at "S3 Copy Status". From EC2Worker logs, I can see the gov-cloud-import.js is trying to start with different node PIDs but never reaches running state.

Wed Mar 20 2019 08:25:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2765
Wed Mar 20 2019 08:30:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2878
Wed Mar 20 2019 08:35:01 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2995
Wed Mar 20 2019 08:40:03 GMT+0000 (UTC) gov-cloud-import.js is starting Node PID: 2137

**Comment by awsjason** [comment]
Some error is happening and nodejs is restarting. I'd suggest starting with terminating the EC2 and starting a new copy.  If for some reason the failure still occurs, you can either attempt to uninstall the cloudformations templates and reinstall.  Otherwise you can get on the EC2Worker to see why nodejs is restarting itself.  Either way, your job never really got started if you don't see it in log.

**Comment by AmudhaNila** [comment]
Issue was due to missing gov-cloud-import.js file in the EC2 instance. After manually pasting it under /home/ec2-user/ the copy succeeded and Image copy was successful. Not sure how gov-cloud-import.js was missed.

**Comment by awsjason** [comment]
Ah, ok.  You can always look at the cloud-init log to show you if there was an error during the user-data script.  Please open another issue if something arises!  😀
