### ISSUE TITLE
Can't import an image > 1024GB

### ISSUE THREAD

**Issue by todds02** [awslabs/aws-gov-cloud-import#13]
Attemping to import an image > 1024GiB fails at the MakeVolume step.  It looks like the issue is in the makeVolume function in makeVolume/index.js.  It does not specify the VolumeType parameter, which according to AWS docs causes it to default to 'standard', which has the 1024GiBs limit.

The diff below allowed my import to proceed - although I'm still failing at a later stage, so I'm not 100% sure this is the proper fix. Also not sure if this is something that would be configurable due to cost or other issue.

diff --git a/lambda/makeVolume/index.js b/lambda/makeVolume/index.js
index 627c633..2595782 100644
--- a/lambda/makeVolume/index.js
+++ b/lambda/makeVolume/index.js
@@ -74,6 +74,7 @@ function makeVolume(az, snapshotId){
         let params = {
             AvailabilityZone: az,
             SnapshotId: snapshotId,
+            VolumeType: 'gp2',
             TagSpecifications: [
               {
                 ResourceType: 'volume',

**Comment by awsjason** [comment]
This issue wont be with the makeVolume lambda, as its only 8GB.  Everything flows throw memory, although S3FS does cache some info while transfering on the volume.  The nodejs script that runs on the EC2 limits the size due to S3 part limit.  1TB was set a safety limit.  

If you want to attempt to color outside the lines, you want to mess and test with gov-cloud-import.js and the copyVolume function (line 474) that runs on the EC2.  The other factor will be the time allotted in StepFunctions to finish.  You can change the timeout for the activity:ec2s3Copy.  You may want to double it since the timers for testing was using 1TB images.

**Comment by awsjason** [comment]
Wanted to check back to see if there was any help needed.   One correction from above, stated 1TB for testing images and meant 100GB.  1TB is for S3 Bucket sync.
